center_point = [0.25, 0.75]
density = 30.0

[[line_segment]]
start = [-1.0, 0.0]
end = [3.5, 0.0]

[[line_segment]]
start = [3.5, 0.0]
end = [2, 2]

[[line_segment]]
start = [2, 2]
end = [0.0, 2]

[[line_segment]]
start = [0.0, 2]
end = [-1.0, 0.0]