center_point = [0.0, 0.0]
density = 30.0

[[line_segment]]
start = [0.0, 0.0]
end = [5, 0.0]

[[line_segment]]
start = [5, 0.0]
end = [3.0, 2.5]

[[line_segment]]
start = [3.0, 2.5]
end = [0.0, 2.5]

[[line_segment]]
start = [0.0, 2.5]
end = [0.0, 0.0]