center_point = [0.0, 0.0]

[[line_segment]]
start = [0.0, 0.0]
end = [0.0, 25.0]
density = 30.0

[[line_segment]]
start = [25.0, 0.0]
end = [25.0, 50.0]
density = 30.0

[[line_segment]]
start = [25.0, 50.0]
end = [0.0, 50.0]
density = 30.0

[[line_segment]]
start = [0.0, 50.0]
end = [0.0, 0.0]
density = 30.0