center_point = [0.0, 0.0]
density = 30.0

[[line_segment]]
start = [0.0, 0.0]
end = [2.5, 0.0]

[[line_segment]]
start = [2.5, 0.0]
end = [2.5, 5.0]

[[line_segment]]
start = [2.5, 5.0]
end = [0.0, 5.0]

[[line_segment]]
start = [0.0, 5.0]
end = [0.0, 0.0]