center_point = [1.5, 1.0]
density = 30.0

[[line_segment]]
start = [0.0, 0.0]
end = [2.5, 0.0]

[[line_segment]]
start = [2.5, 0.0]
end = [2, 2]

[[line_segment]]
start = [2, 2]
end = [0.0, 2]

[[line_segment]]
start = [0.0, 2]
end = [0.0, 0.0]