[package]
name = "slc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*", "examples/*"]

[dependencies]
slc_core = { path = "crates/slc_core" }
slc_output = { path = "crates/slc_output" }
slc_input = { path = "crates/slc_input" }
slc_gui_output = { path = "crates/slc_gui_output" }


[[example]]
name = "gui"
path = "examples/gui.rs"
