[package]
name = "sled"
version = "0.2.0"
edition = "2021"
rust-version = "1.70"

[features]
default = ["drivers", "scheduler"]
drivers = ["compact_str"]
scheduler = ["spin_sleep"]
named_colors = []

[dependencies]
glam = { version = "0.27", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
palette = { version = "0.7", default-features = false, features = [
    "std",
    "approx",
] }
toml = "0.8"
smallvec = "1.13"
compact_str = { version = "0.7", optional = true }
spin_sleep = { version = "1.2", optional = true }

[dev-dependencies]
criterion = {version = "0.5.1", default-features = false, features = ["cargo_bench_support"]}
ratatui = "0.26"
crossterm = {version = "0.27.0"}
rand = {version = "0.8.5", default-features = false, features = ["std", "std_rng"]}

[profile.bench]
lto = true

[profile.release]
strip = "debuginfo"
lto = true

[[bench]]
name = "comet"
harness = false

[[bench]]
name = "ripples"
harness = false

[lib]
bench = false
