[package]
name = "sled"
version = "0.2.0"
edition = "2021"

[dependencies]
glam = { version = "0.24.2", features = ["serde"] }
serde = "1.0.188"
palette = { version = "0.7.3", default-features = false, features = [
    "serializing",
    "std",
    "approx",
] }
toml = "0.8.0"

[dev-dependencies]
criterion = "0.5.1"

[profile.bench]
lto = true

[[example]]
name = "basic"
path = "examples/basic.rs"
doc-scrape-examples = true

[[bench]]
name = "my_benchmark"
harness = false

