name: Run Benchmarks
on: [pull_request]

jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.7.5
        with:
          workspaces: spatial_led

      - uses: boa-dev/criterion-compare-action@v3
        with:
          # Needed. The name of the branch to compare with. This default uses the branch which is being pulled against
          branchName: ${{ github.base_ref }}