name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # - name: Build
    #   working-directory: ./sled
    #   run: cargo build
      
    # - name: Run tests
    #   working-directory: ./sled
    #   run: cargo test

    - name: Run benchmark
      working-directory: ./sled
      run: cargo bench map | tee output.txt;echo "outputting file here:"; cat output.txt

    - name: Store benchmark results
      uses: benchmark-action/github-action-benchmark@v1
      with: 
        tool: 'cargo'
        output-file-path: sled/output.txt

            
