name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./sled
      run: cargo build
      
    - name: Run tests
      working-directory: ./sled
      run: cargo test

    - name: Run benchmarks
      uses: benchmark-action/github-action-benchmark@v1.18.0
      with: 
        working-directory: ./sled
        tool: 'cargo'
        output-file-path: output.txt

            
