name: Build and Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2.7.5
      with:
        workspaces: spatial_led

    - name: Build
      run: cargo build
      
    - name: Run tests
      run: cargo test